spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/deal
    username: myuser
    password: secret

  application:
    name: deal


  jwt:
    jwtSecret: "verysecretkey-should-be-at-least-256-bits-long!"

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: /db/changelog/changelog.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
server:
  port: 8081
